language: go

go:
  - "1.10"

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

script:
  - go test -race ./model
  - go test -race ./datalayer
  - go test -race ./request
  - go test -race ./api-aws/*/
  - cd ./api-aws/ && make