language: go

go:
  - "1.10"

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

script:
  - go test -race ./model
  - go test -race ./datalayer
  - go test -race ./request
  - go test -race ./api-aws/*/
  - cd ./api-aws/ && make

before_deploy:
  - cd ..
  - npm install -g serverless

deploy:
  # deploy to production if commit is tagged
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    tags: true