language: go

go:
  - "1.10"

before_install:
  - go get -t ./datalayer
  - go get -t ./request
  - go get -t ./api-aws/*/

script:
  - go test -race ./datalayer
  - go test -race ./request
  - go test -race ./api-aws/*/